name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/undrawwelcomecatsthqn-1.png
    - assets/page-1/images/group-6.png
    - assets/page-1/images/group-4.png
    - assets/page-1/images/group-4-rja.png
    - assets/page-1/images/group-3.png
    - assets/page-1/images/group-15.png
    - assets/page-1/images/undrawdatareports706v.png
    - assets/page-1/images/group-15-Hc4.png
    - assets/page-1/images/group-9.png
    - assets/page-1/images/group-11.png
    - assets/page-1/images/group-15-KV2.png
    - assets/page-1/images/profile-3.png
    - assets/page-1/images/history-3.png
    - assets/page-1/images/home-2.png
    - assets/page-1/images/profile-3-sbv.png
    - assets/page-1/images/group-6-QMe.png
    - assets/page-1/images/group-15-iqN.png
    - assets/page-1/images/ellipse-6.png
    - assets/page-1/images/group-15-c5N.png
    - assets/page-1/images/nikepng18.png
    - assets/page-1/images/history-3-k6t.png
    - assets/page-1/images/polygon-2.png
    - assets/page-1/images/profile-3-Exx.png
    - assets/page-1/images/group-6-GiL.png
    - assets/page-1/images/nikepng18-gZE.png
    - assets/page-1/images/ellipse-6-B2p.png
    - assets/page-1/images/ellipse-6-yn8.png
    - assets/page-1/images/nikepng18-9jn.png
    - assets/page-1/images/rectangle-16.png
    - assets/page-1/images/group-10.png
    - assets/page-1/images/nikepng18-Ytx.png
    - assets/page-1/images/polygon-3.png
    - assets/page-1/images/group-15-78U.png
    - assets/page-1/images/group-6-1yS.png
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/home-2-aSC.png
    - assets/page-1/images/nikepng18-LCQ.png
    - assets/page-1/images/applelogopng19688.png
    - assets/page-1/images/applelogopng19688-bh2.png
    - assets/page-1/images/applelogopng19688-iqW.png
    - assets/page-1/images/ellipse-6-iW4.png
    - assets/page-1/images/group-15-NqW.png
    - assets/page-1/images/polygon-3-LXS.png
    - assets/page-1/images/group-15-3Tn.png
    - assets/page-1/images/group-15-upk.png
    - assets/page-1/images/nikepng18-q5S.png
    - assets/page-1/images/applelogopng19688-ww6.png
    - assets/page-1/images/ellipse-10.png
    - assets/page-1/images/group-15-n8x.png
    - assets/page-1/images/nikepng18-8Ti.png
    - assets/page-1/images/nikepng18-yz8.png
    - assets/page-1/images/.png
    - assets/page-1/images/group-15-DDa.png
    - assets/page-1/images/vector-2.png
    - assets/page-1/images/applelogopng19688-Wdv.png
    - assets/page-1/images/auto-group-tlfa.png
    - assets/page-1/images/home-2-G1W.png
    - assets/page-1/images/applelogopng19688-83i.png
    - assets/page-1/images/vector-1-UtG.png
    - assets/page-1/images/-PVS.png
    - assets/page-1/images/group-15-MSG.png
    - assets/page-1/images/group-11-XLk.png
    - assets/page-1/images/nikepng18-HfE.png
    - assets/page-1/images/nikepng18-qAx.png
    - assets/page-1/images/applelogopng19688-nrt.png
    - assets/page-1/images/applelogopng19688-Mf6.png
    - assets/page-1/images/vector-1-Eqv.png
    - assets/page-1/images/uberlogoblackrgb.png
    - assets/page-1/images/group-3-qC4.png
    - assets/page-1/images/group-15-kBr.png
    - assets/page-1/images/vector-2-JDN.png
    - assets/page-1/images/home-2-bNp.png
    - assets/page-1/images/vector-1-ZrY.png
    - assets/page-1/images/ellipse-9-bg.png
    - assets/page-1/images/uberlogoblackrgb-FpU.png
    - assets/page-1/images/group-15-Kjn.png
    - assets/page-1/images/applelogopng19688-VbW.png
    - assets/page-1/images/nikepng18-yTv.png
    - assets/page-1/images/nikepng18-qBE.png
    - assets/page-1/images/history-3-yHr.png
    - assets/page-1/images/nikepng18-WDn.png
    - assets/page-1/images/uberlogoblackrgb-Rbe.png
    - assets/page-1/images/applelogopng19688-5SY.png
    - assets/page-1/images/applelogopng19688-R92.png
    - assets/page-1/images/nikepng18-SJC.png
    - assets/page-1/images/rectangle-1.png
    - assets/page-1/images/polygon-2-3kL.png
    - assets/page-1/images/nikepng18-NEC.png
    - assets/page-1/images/applelogopng19688-6oi.png
    - assets/page-1/images/group-6-JhE.png
    - assets/page-1/images/ellipse-6-WFi.png
    - assets/page-1/images/uberlogoblackrgb-sWp.png
    - assets/page-1/images/nikepng18-mJg.png
    - assets/page-1/images/group-15-bC4.png
    - assets/page-1/images/vector-2-ykt.png
    - assets/page-1/images/history-3-kAL.png
    - assets/page-1/images/nikepng18-ojE.png
    - assets/page-1/images/nikepng18-S56.png
    - assets/page-1/images/applelogopng19688-trC.png
    - assets/page-1/images/applelogopng19688-CEU.png
    - assets/page-1/images/profile-3-sua.png
    - assets/page-1/images/applelogopng19688-X7E.png
    - assets/page-1/images/vector-2-giL.png
    - assets/page-1/images/vector-2-1ex.png
    - assets/page-1/images/vector-1-7TE.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
